
name: AutoBuild
 
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
     run:
      shell: bash
      working-directory: frontend
    
    steps:
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDDTHHmmss
          utcOffset: "+08:00"

#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
#        with:
#         node-version: '^14'
#
#      - name: Install JS Dep
#        run: pwd && yarn install
#
#      - name: Build
#        run: yarn run build --modern
#
#      - name: Pack files
#        run: tar zcvf ./frontend.tar.gz -C ./dist .
       
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.current-time.outputs.formattedTime }}"
          prerelease: true
          files: |
            *.xmind
            *.tar.gz
            yarn.lock
        
        
